sudo: false
language: node_js
node_js: 12
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: r.zeraatkar1992@gmail.com
script: npm run val
after_success:
  - npm run report-coverage
